---
###########################
###########################
## Jest GitHub Actions ##
###########################
###########################
name: Jest Unit test

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [TestBranch]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Jest unit test
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
